 const StudentsTypes = {
    FETCH_STUDENTS_START: "FETCH_STUDENTS_START",
    FETCH_STUDENTS_SUCCESS: "FETCH_STUDENTS_SUCCESS",
    FETCH_STUDENTS_ERROR: "FETCH_STUDENTS_ERROR"
}

export default StudentsTypes;