const TeachersTypes = {
    FETCH_TEACHER_START: "FETCH_TEACHER_START",
    FETCH_TEACHER_SUCCESS: "FETCH_TEACHER_SUCCESS",
    FETCH_TEACHER_ERROR: "FETCH_TEACHER_ERROR" 
}

export default TeachersTypes